# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'dami-service-connection'
  azureResourceGroup: bicep
  subscriptionId: '85c7908d-8028-4894-af5d-1991ee8f0450'
  key: 'terraform.tfstate'
  container: 'damicontainertf'

jobs:
- job: TerraformInit
  steps:
  - task: TerraformTaskV3@3
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: '${subscriptionId}'
      backendAzureRmResourceGroupName: '${azureResourceGroup}'
      backendAzureRmStorageAccountName: '${damiteststorage}'
      backendAzureRmContainerName: '${container}'
      backendAzureRmKey: '${key}'
    
- job: TerraformApply
  steps:
  - task: TerraformTaskV3@3
    displayName: Plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      commandOptions: '-out=tfplan'
      environmentServiceNameAzureRM: 'Visual Studio Enterprise(85c7908d-8028-4894-af5d-1991ee8f0450)'

